name: Continuous Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches:
      - "main"
  # https://docs.github.com/es/actions/using-workflows/events-that-trigger-workflows
  workflow_run:
    workflows: [ci]
    types:
      - completed

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy_production:
    name: "Deploy to production"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

     
